language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  app: one-two-tie-your-shoe
  api_key:
    secure: WJjsGVKm5G2HEbpPbbJtqcahGIxktipazqra01rqabN6j+qBqziOFOkhK7FfCOA9sNtgyBUNM6yvLG3ve/vURxupHguwBo+wJ5HBCNkwveCBnD1vXgVq2eSl9NX3vfZGzNMqoHGevBfxC+AK4dqFmTiA40i1boQ0m7nLNPM4VeVxr5Lld1yWhGm/fJjxNAsjw7WCCtK3yXHbsxUpSj0ZgWSEzgIxHruTGF/BCop4/DSGScm0ZphSkqjdzTFiWzKC51/odnToDkx/2MLGRW6qM75mLrCyOhc2EsqIlZ1jt9BE19On3ZLjpKjW23gTtqs+9ByY2KKyi5us+E59k7nEpG/mERjdGdjqpmiVoERsBCmNMSmyulxbk5F/8OodF15ibYM1b4b5z+yH9fnJa6ixh+AG5ourxIwzI82ABByX6bGzf5uhPt/vScEY9M8X228feg19oO3+mc7pubaHlBHc34MeJYMzA6MMbYwmJpXPmcQFpoSknwLEOFJ1AGuDbZI7bySVI6tRBpk4zY4dEQ1+mkddcY2DnLNPs80cYgc0dwPOA1H4n2nyyrNZ4gxn/Zi+qTst9g725CIENEq2pPFtBil99fO6xtEPRMlo9NphgAxY49lIHMVZIdl2GjQlJv0cjeINTyNLZqQYYj3eEam9uwkp19OW+A7x3ikR9viP4qI=
